apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    service: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: tebohoxthapeli/reverse-proxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
spec:
  selector:
    service: reverse-proxy
  ports:
    - name: 8080
      protocol: TCP
      port: 8080
      targetPort: 8080
